export const departmentImageMap: Record<string, string> = {
  cardiology: '/assets/images/departments/Cardiology.jpeg',
  dentistry: '/assets/images/departments/Dentistry.jpeg',
  dermatology: '/assets/images/departments/Dermatology.jpeg',
  endocrinology: '/assets/images/departments/Endocrinology.jpeg',
  gastroenterology: '/assets/images/departments/gastroenterology.jpg',
  generalsurgery: '/assets/images/departments/GeneralSurgery.jpeg',
  gynae: '/assets/images/departments/Gynae.jpeg',
  medicine_infectious_disease: '/assets/images/departments/Medicine.jpeg',
  nephrology: '/assets/images/departments/Nephrology.jpeg',
  neurology: '/assets/images/departments/Neurology.jpeg',
  neurosurgery: '/assets/images/departments/Neurosurgery.jpeg',
  orthopedic: '/assets/images/departments/Orthopedic.jpeg',
  ophthalmology: '/assets/images/departments/Ophthalmology.jpeg',
  paediatrics: '/assets/images/departments/Paediatrics.jpeg',
  pathology: '/assets/images/departments/Pathology.jpeg',
  psychiatry: '/assets/images/departments/Psychiatry.jpeg',
  radiology: '/assets/images/departments/Radiology.jpeg',
  urology: '/assets/images/departments/Urology.jpeg',
  psychology: '/assets/images/departments/Psychology.jpeg',

  psychiatrist: '/assets/images/departments/Psychiatry.jpeg',
  dietetics: '/assets/images/departments/Dietetics.jpeg',
  speech_therapy: '/assets/images/departments/SpeechTherapy.jpeg',
  audiology: '/assets/images/departments/Audiology.jpeg',
  hepatology_liver_transplant: '/assets/images/departments/Hepatology.jpeg',
  physiotherapy: '/assets/images/departments/Physiotherapy.jpeg',
  bariatric_surgery: '/assets/images/departments/BariatricSurgery.jpeg',
  liver_surgery: '/assets/images/departments/LiverSurgery.jpeg',
  geriatrics_elderly_care: '/assets/images/departments/Geriatrics.jpeg',
  nuclear_medicine: '/assets/images/departments/NuclearMedicine.jpeg',
  paediatrics_surgery: '/assets/images/departments/PaediatricSurgery.jpeg',
  cath_laboratory: '/assets/images/departments/CathLab.jpeg',
  ccu: '/assets/images/departments/CCU.jpeg',
  covid_vaccination_center: '/assets/images/departments/CovidVaccination.jpeg',
  ct_icu: '/assets/images/departments/CTICU.jpeg',
  emergency: '/assets/images/departments/Emergency.jpg',
  hdu_ipd_1: '/assets/images/departments/HDU.jpeg',
  icu: '/assets/images/departments/ICU.jpeg',
  ipd: '/assets/images/departments/IPD.jpeg',
  ld_postnatal: '/assets/images/departments/L&D&POSTNATAL.jpeg',
  laboratory: '/assets/images/departments/LABORATORY.jpeg',
  nicu: '/assets/images/departments/NICU.jpeg',
  picu: '/assets/images/departments/Picu.jpeg',
  rehabilitation: '/assets/images/departments/Rehabilitation.jpeg',
  dietitian: '/assets/images/departments/Dietitian.jpeg',
  vascular_surgery: '/assets/images/departments/VascularSurgery.jpeg',
  pain_management: '/assets/images/departments/PainManagement.jpeg',
  kidney_transplant: '/assets/images/departments/KidneyTransplant.jpeg',
  cardiac_surgery: '/assets/images/departments/CardiacSurgery.jpeg',
  anesthesiologist: '/assets/images/departments/Anesthesiologist.jpeg',
  bone_marrow_transplant: '/assets/images/departments/BoneMarrowTransplant.jpeg',
  dental: '/assets/images/departments/Dental.jpeg',
  ent: '/assets/images/departments/ENT.jpeg',
  head_neck_surgery: '/assets/images/departments/HeadNeckSurgery.jpeg',
  internal_medicine: '/assets/images/departments/InternalMedicine.jpeg',
  critical_care: '/assets/images/departments/CriticalCare.jpeg',
  operation_room_anaesthesia: '/assets/images/departments/OperationRoom.jpeg',
  dialysis: '/assets/images/departments/Dialysis.jpeg',
  liver_icu: '/assets/images/departments/LiverICU.jpeg',
  haematology: '/assets/images/departments/Haematology.jpeg',
  oral_maxillofacial_surgery: '/assets/images/departments/OralMaxillofacial.jpeg',
  rheumatologist: '/assets/images/departments/Rheumatology.jpeg',
  plastic_surgery: '/assets/images/departments/PlasticSurgery.jpeg',
  oncology: '/assets/images/departments/ONCOLOGY.jpeg',
  pulmonologist: '/assets/images/departments/Pulmonologist.jpeg',
  anesthesia: '/assets/images/departments/Anesthesia.jpeg',
  peads_psychologist: '/assets/images/departments/PaedsPsychologist.jpeg',
  geriatrician_medical_specialist: '/assets/images/departments/Geriatrics.jpeg',
  paeds_surgeon: '/assets/images/departments/PaedsSurgeon.jpeg',
  diabetology: '/assets/images/departments/Diabetology.jpeg',
  others: '/assets/images/departments/default.jpeg',
}

export const getDepartmentImage = (title: string) => {
  const key = title
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z\s]/g, '')
    .trim()

  return departmentImageMap[key] || '/assets/images/departments/default.jpeg'
}
